version: 2
updates:
- package-ecosystem: "github-actions"
  open-pull-requests-limit: 999
  directory: "/"
  rebase-strategy: "disabled"
  schedule:
    interval: weekly
    day: "saturday"
    timezone: "Europe/Berlin"
    time: "03:00"
- package-ecosystem: npm
  open-pull-requests-limit: 999
  directory: "/"
  rebase-strategy: "disabled"
  schedule:
    interval: weekly
    day: "saturday"
    timezone: "Europe/Berlin"
    time: "03:00"
- package-ecosystem: docker
  open-pull-requests-limit: 999
  directory: "/"
  rebase-strategy: "disabled"
  schedule:
    interval: weekly
    day: "saturday"
    timezone: "Europe/Berlin"
    time: "03:00"

# presenter
- package-ecosystem: npm
  open-pull-requests-limit: 999
  directory: "/presenter"
  rebase-strategy: "disabled"
  schedule:
    interval: weekly
    day: "saturday"
    timezone: "Europe/Berlin"
    time: "03:00"
- package-ecosystem: docker
  open-pull-requests-limit: 999
  directory: "/presenter"
  rebase-strategy: "disabled"
  schedule:
    interval: weekly
    day: "saturday"
    timezone: "Europe/Berlin"
    time: "03:00"

# admin
- package-ecosystem: npm
  open-pull-requests-limit: 999
  directory: "/admin"
  rebase-strategy: "disabled"
  schedule:
    interval: weekly
    day: "saturday"
    timezone: "Europe/Berlin"
    time: "03:00"
- package-ecosystem: docker
  open-pull-requests-limit: 999
  directory: "/admin"
  rebase-strategy: "disabled"
  schedule:
    interval: weekly
    day: "saturday"
    timezone: "Europe/Berlin"
    time: "03:00"

# frontend
- package-ecosystem: npm
  open-pull-requests-limit: 999
  directory: "/frontend"
  rebase-strategy: "disabled"
  schedule:
    interval: weekly
    day: "saturday"
    timezone: "Europe/Berlin"
    time: "03:00"
- package-ecosystem: docker
  open-pull-requests-limit: 999
  directory: "/frontend"
  rebase-strategy: "disabled"
  schedule:
    interval: weekly
    day: "saturday"
    timezone: "Europe/Berlin"
    time: "03:00"

# backend
- package-ecosystem: npm
  open-pull-requests-limit: 999
  directory: "/backend"
  rebase-strategy: "disabled"
  schedule:
    interval: weekly
    day: "saturday"
    timezone: "Europe/Berlin"
    time: "03:00"
- package-ecosystem: docker
  open-pull-requests-limit: 999
  directory: "/backend"
  rebase-strategy: "disabled"
  schedule:
    interval: weekly
    day: "saturday"
    timezone: "Europe/Berlin"
    time: "03:00"
