version: 2
updates:
- package-ecosystem: "github-actions"
  directory: "/"
  rebase-strategy: "disabled"
  schedule:
    interval: weekly
    day: "saturday"
    timezone: "Europe/Berlin"
    time: "03:00"
- package-ecosystem: docker
  directory: "/"
  rebase-strategy: "disabled"
  schedule:
    interval: weekly
    day: "saturday"
    timezone: "Europe/Berlin"
    time: "03:00"
# presenter
- package-ecosystem: npm
  directory: "/presenter"
  rebase-strategy: "disabled"
  schedule:
    interval: weekly
    day: "saturday"
    timezone: "Europe/Berlin"
    time: "03:00"
- package-ecosystem: docker
  directory: "/presenter"
  rebase-strategy: "disabled"
  schedule:
    interval: weekly
    day: "saturday"
    timezone: "Europe/Berlin"
    time: "03:00"
# backend
- package-ecosystem: npm
  directory: "/backend"
  rebase-strategy: "disabled"
  schedule:
    interval: weekly
    day: "saturday"
    timezone: "Europe/Berlin"
    time: "03:00"
- package-ecosystem: docker
  directory: "/backend"
  rebase-strategy: "disabled"
  schedule:
    interval: weekly
    day: "saturday"
    timezone: "Europe/Berlin"
    time: "03:00"
