# These file filter patterns are used by the action https://github.com/dorny/paths-filter

test-code: &test-code
  - '**/*'

# presenter
presenter-test-lint-code: &presenter-test-lint-code
  - 'presenter/**/*'

presenter-test-unit-code: &presenter-test-unit-code
  - '.github/workflows/presenter.test.unit.code.yml'
  - '.github/file-filters.yml'
  - 'presenter/!(.vuepress)/**/*!(.md)'

presenter-test-build-code: &presenter-test-build-code
  - '.github/workflows/presenter.test.build.code.yml'
  - '.github/file-filters.yml'
  - 'presenter/!(.vuepress)/**/*!(.md)'

presenter-test-build-docker: &presenter-test-build-docker
  - '.github/workflows/presenter.test.build.docker.yml'
  - '.github/file-filters.yml'
  - 'presenter/!(.vuepress)/**/*!(.md)'

presenter-test-build-docs: &presenter-test-build-docs
  - '.github/workflows/presenter.test.build.docs.yml'
  - '.github/file-filters.yml'
  - 'presenter/**/*.md'
  - 'presenter/.vuepress/*'
  - 'presenter/package.json'

presenter-test-build-storybook: &presenter-test-build-storybook
  - '.github/workflows/presenter.test.build.storybook.yml'
  - '.github/file-filters.yml'
  - 'presenter/!(.vuepress)/**/*!(.md)'

# frontend
frontend-test-lint-code: &frontend-test-lint-code
  - 'frontend/**/*'

frontend-test-unit-code: &frontend-test-unit-code
  - '.github/workflows/frontend.test.unit.code.yml'
  - '.github/file-filters.yml'
  - 'frontend/!(.vuepress)/**/*!(.md)'

frontend-test-build-code: &frontend-test-build-code
  - '.github/workflows/frontend.test.build.code.yml'
  - '.github/file-filters.yml'
  - 'frontend/!(.vuepress)/**/*!(.md)'

frontend-test-build-docker: &frontend-test-build-docker
  - '.github/workflows/frontend.test.build.docker.yml'
  - '.github/file-filters.yml'
  - 'frontend/!(.vuepress)/**/*!(.md)'

frontend-test-build-docs: &frontend-test-build-docs
  - '.github/workflows/frontend.test.build.docs.yml'
  - '.github/file-filters.yml'
  - 'frontend/**/*.md'
  - 'frontend/.vuepress/*'
  - 'frontend/package.json'

frontend-test-build-storybook: &frontend-test-build-storybook
  - '.github/workflows/frontend.test.build.storybook.yml'
  - '.github/file-filters.yml'
  - 'frontend/!(.vuepress)/**/*!(.md)'

# admin
admin-test-lint-code: &admin-test-lint-code
  - 'admin/**/*'

admin-test-unit-code: &admin-test-unit-code
  - '.github/workflows/admin.test.unit.code.yml'
  - '.github/file-filters.yml'
  - 'admin/!(.vuepress)/**/*!(.md)'

admin-test-build-code: &admin-test-build-code
  - '.github/workflows/admin.test.build.code.yml'
  - '.github/file-filters.yml'
  - 'admin/!(.vuepress)/**/*!(.md)'

admin-test-build-docker: &admin-test-build-docker
  - '.github/workflows/admin.test.build.docker.yml'
  - '.github/file-filters.yml'
  - 'admin/!(.vuepress)/**/*!(.md)'

admin-test-build-docs: &admin-test-build-docs
  - '.github/workflows/admin.test.build.docs.yml'
  - '.github/file-filters.yml'
  - 'admin/**/*.md'
  - 'admin/.vuepress/*'
  - 'admin/package.json'

admin-test-build-storybook: &admin-test-build-storybook
  - '.github/workflows/admin.test.build.storybook.yml'
  - '.github/file-filters.yml'
  - 'admin/!(.vuepress)/**/*!(.md)'

# backend
backend-test-lint-code: &backend-test-lint-code
  - 'backend/**/*'

backend-test-unit-code: &backend-test-unit-code
  - '.github/workflows/backend.test.unit.code.yml'
  - '.github/file-filters.yml'
  - 'backend/!(.vuepress)/**/*!(.md)'

backend-test-build-code: &backend-test-build-code
  - '.github/workflows/backend.test.build.code.yml'
  - '.github/file-filters.yml'
  - 'backend/!(.vuepress)/**/*!(.md)'

backend-test-build-docker: &backend-test-build-docker
  - '.github/workflows/backend.test.build.docker.yml'
  - '.github/file-filters.yml'
  - 'backend/!(.vuepress)/**/*!(.md)'

backend-test-build-docs: &backend-test-build-docs
  - 'backend/.github/workflows/backend.test.build.docs.yml'
  - '.github/file-filters.yml'
  - 'backend/**/*.md'
  - 'backend/.vuepress/*'
  - 'backend/package.json'