# These file filter patterns are used by the action https://github.com/dorny/paths-filter

test-code: &test-code
  - '**/*'

# presenter
presenter-test-lint-code: &presenter-test-lint-code
  - 'presenter/**/*'

presenter-test-unit-code: &presenter-test-unit-code
  - 'presenter/**/*'

presenter-test-build-code: &presenter-test-build-code
  - 'presenter/**/*'

presenter-test-build-docker: &presenter-test-build-docker
  - 'presenter/**/*'

presenter-test-build-docs: &presenter-test-build-docs
  - 'presenter/**/*.md'
  - 'presenter/.vuepress/*'

presenter-test-build-storybook: &presenter-test-build-storybook
  - 'presenter/**/*'

# frontend
frontend-test-lint-code: &frontend-test-lint-code
  - 'frontend/**/*'

frontend-test-unit-code: &frontend-test-unit-code
  - 'frontend/**/*'

frontend-test-build-code: &frontend-test-build-code
  - 'frontend/**/*'

frontend-test-build-docker: &frontend-test-build-docker
  - 'frontend/**/*'

frontend-test-build-docs: &frontend-test-build-docs
  - 'frontend/**/*.md'
  - 'frontend/.vuepress/*'

frontend-test-build-storybook: &frontend-test-build-storybook
  - 'frontend/**/*'

# backend
backend-test-lint-code: &backend-test-lint-code
  - 'backend/**/*'

backend-test-unit-code: &backend-test-unit-code
  - 'backend/**/*'

backend-test-build-code: &backend-test-build-code
  - 'backend/**/*'

backend-test-build-docker: &backend-test-build-docker
  - 'backend/**/*'

backend-test-build-docs: &backend-test-build-docs
  - 'backend/**/*.md'
  - 'backend/.vuepress/*'