# These file filter patterns are used by the action https://github.com/dorny/paths-filter

test-code: &test-code
  - '**/*'

# presenter
presenter-test-lint-code: &presenter-test-lint-code
  - 'presenter/**/*'

presenter-test-unit-code: &presenter-test-unit-code
  - 'presenter/**/*'

presenter-test-build-code: &presenter-test-build-code
  - 'presenter/**/*'

presenter-test-build-docker: &presenter-test-build-docker
  - 'presenter/**/*'

presenter-test-build-docs: &presenter-test-build-docs
  - 'presenter/**/*.md'
  - 'presenter/.github/workflows/presenter.deploy.docs.yml'
  - 'presenter/.vuepress/*'
  - 'presenter/package.json'

presenter-test-build-storybook: &presenter-test-build-storybook
  - 'presenter/**/*'

# frontend
frontend-test-lint-code: &frontend-test-lint-code
  - 'frontend/**/*'

frontend-test-unit-code: &frontend-test-unit-code
  - 'frontend/**/*'

frontend-test-build-code: &frontend-test-build-code
  - 'frontend/**/*'

frontend-test-build-docker: &frontend-test-build-docker
  - 'frontend/**/*'

frontend-test-build-docs: &frontend-test-build-docs
  - 'frontend/**/*.md'
  - 'frontend/.github/workflows/frontend.deploy.docs.yml'
  - 'frontend/.vuepress/*'
  - 'frontend/package.json'

frontend-test-build-storybook: &frontend-test-build-storybook
  - 'frontend/**/*'

# admin
admin-test-lint-code: &admin-test-lint-code
  - 'admin/**/*'

admin-test-unit-code: &admin-test-unit-code
  - 'admin/**/*'

admin-test-build-code: &admin-test-build-code
  - 'admin/**/*'

admin-test-build-docker: &admin-test-build-docker
  - 'admin/**/*'

admin-test-build-docs: &admin-test-build-docs
  - 'admin/**/*.md'
  - 'admin/.github/workflows/admin.deploy.docs.yml'
  - 'admin/.vuepress/*'
  - 'admin/package.json'

admin-test-build-storybook: &admin-test-build-storybook
  - 'admin/**/*'


# backend
backend-test-lint-code: &backend-test-lint-code
  - 'backend/**/*'

backend-test-unit-code: &backend-test-unit-code
  - 'backend/**/*'

backend-test-build-code: &backend-test-build-code
  - 'backend/**/*'

backend-test-build-docker: &backend-test-build-docker
  - 'backend/**/*'

backend-test-build-docs: &backend-test-build-docs
  - 'backend/**/*.md'
  - 'backend/.github/workflows/backend.deploy.docs.yml'
  - 'backend/.vuepress/*'
  - 'backend/package.json'