version: '3.4'

services:
  #######################################################
  # FRONTEND ############################################
  #######################################################
  frontend:
    image: it4c/frontend:local-test
    build:
      target: test
    environment:
      - NODE_ENV=production

volumes:
  frontend_node_modules:
