version: '3.4'

services:
  #######################################################
  # FRONTEND ############################################
  #######################################################
  frontend:
    image: dreammall/frontend:local-test
    build:
      context: .
      target: test
    networks:
      - external-net
      - internal-net
    ports:
      - 3000:3000
    environment:
      # Envs used in Dockerfile
      # - DOCKER_WORKDIR="/app"
      # - PORT=3000
      # - BUILD_DATE="1970-01-01T00:00:00.00Z"
      # - BUILD_VERSION="0.0.0.0"
      # - BUILD_COMMIT="0000000"
      - NODE_ENV=production

networks:
  external-net:
  internal-net:
    internal: true
