include:
  - path:
    - ./authentik/docker-compose.yml
    - ./authentik/docker-compose.override.yml

services:
  frontend:
    build:
      target: development
    ports:
      # development server port
      - 24679:24679
    environment:
      - NODE_ENV=development
      - PORT_HMR=24679
    volumes:
      - ./frontend:/app

  frontend-storybook:
    build:
      context: ./frontend
      target: storybook
    ports:
      - 6007:6006
    environment:
      - NODE_ENV=development
    volumes:
      - ./frontend:/app

  backend:
    build:
      context: ./backend
      target: development
    environment:
      - NODE_ENV=development
    volumes:
      - ./backend:/server

  migrations:
    build:
      context: ./backend
      target: development
    command: npm run db:migrate
    environment:
      - NODE_ENV=development
    volumes:
      - ./backend:/server

  documentation:
    build:
      target: documentation
    ports:
      - 8080:8080
    environment:
      - NODE_ENV=development
    volumes:
      - ./:/app
