version: "3.4"

services:

  #########################################################
  ## MARIADB ##############################################
  #########################################################
  database:
    networks: 
      - internal-net
      - external-net

  # ######################################################
  # DOCUMENTATION ########################################
  # ######################################################
  documentation:
    # name the image so that it cannot be found in a DockerHub repository, otherwise it will not be built locally from the 'dockerfile' but pulled from there
    image: dreammall/dreammall:local-documentation
    build:
      target: documentation
    environment:
      - NODE_ENV="development"
      # - DEBUG=true
    ports:
      - 8080:8080
    volumes:
      # This makes sure the docker container has its own node modules.
      # Therefore it is possible to have a different node version on the host machine
      - documentation_node_modules:/app/node_modules
      # bind the local folder to the docker to allow live reload
      - ./:/app

  storybook:
    extends:
      file: presenter/docker-compose.override.yml
      service: storybook  

volumes:
  storybook_node_modules:
  documentation_node_modules: