include:
  - ./authentik/docker-compose.yml

services:
  database:
    image: mariadb:10.5
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 3
    environment:
      - MARIADB_ALLOW_EMPTY_PASSWORD=1
      - MARIADB_ALLOW_EMPTY_ROOT_PASSWORD=1
      - MARIADB_USER=root
    ports:
      - 3306:3306
    volumes:
      - db_vol:/var/lib/mysql

  presenter:
    image: ghcr.io/dreammall-earth/dreammall.earth/presenter:latest
    build:
      context: ./presenter
      target: production
    ports:
      - 3001:3000
    environment:
      - NODE_ENV=production

  frontend:
    image: ghcr.io/dreammall-earth/dreammall.earth/frontend:latest
    build:
      context: ./frontend
      target: production
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=production

  backend:
    image: ghcr.io/dreammall-earth/dreammall.earth/backend:latest
    build:
      context: ./backend
      target: production
    depends_on:
      authentik: # because JWKS_URI
        condition: service_started
      database:
        condition: service_started
      migrations:
        condition: service_completed_successfully

    ports:
      - 4000:4000
    environment:
      DATABASE_URL: mysql://root:@database:3306/dreammall.earth
      JWKS_URI: http://authentik:9000/application/o/dreammallearth/jwks/
      NODE_ENV: production

  migrations:
    image: ghcr.io/dreammall-earth/dreammall.earth/backend:latest
    command: npm run db:migrate:deploy
    build:
      context: ./backend
      target: production
    depends_on:
      database:
        condition: service_healthy
    environment:
      DATABASE_URL: mysql://root:@database:3306/dreammall.earth
      NODE_ENV: production

volumes:
  db_vol:
