include:
  - ./authentik/docker-compose.yml

services:
  database:
    image: mariadb:10.5
    environment:
      - MARIADB_ALLOW_EMPTY_PASSWORD=1
      - MARIADB_ALLOW_EMPTY_ROOT_PASSWORD=1
      - MARIADB_USER=root
    ports:
      - 3306:3306
    volumes:
      - db_vol:/var/lib/mysql

  presenter:
    image: roschaefer/dreammall-presenter
    build:
      context: ./presenter
      target: production
    ports:
      - 3001:3000
    env_file:
      presenter/.env
    environment:
      - NODE_ENV=production

  frontend:
    image: roschaefer/dreammall-frontend
    build:
      context: ./frontend
      target: production
    ports:
      - 3000:3000
    env_file:
      frontend/.env
    environment:
      - NODE_ENV=production

  admin:
    image: roschaefer/dreammall-admin
    build:
      context: ./admin
      target: production
    ports:
      - 3002:3000
    env_file:
      admin/.env
    environment:
      - NODE_ENV=production

  backend:
    image: roschaefer/dreammall-backend
    build:
      context: ./backend
      target: production
    depends_on:
      - database
      - authentik
    ports:
      - 4000:4000
    environment:
      DATABASE_URL: mysql://root:@database:3306/dreammall.earth
      JWKS_URI: http://authentik:9000/application/o/dreammallearth/jwks/
      NODE_ENV: production

volumes:
  db_vol:
