version: "3.4"

services:

  #########################################################
  ## MARIADB ##############################################
  #########################################################
  database:
    build:
      context: ./database
      target: mariadb_server
    environment:
      - MARIADB_ALLOW_EMPTY_PASSWORD=1
      - MARIADB_ALLOW_EMPTY_ROOT_PASSWORD=1
      - MARIADB_USER=root
    networks: 
      - internal-net
    ports: 
      - 3306:3306
    volumes: 
      - db_vol:/var/lib/mysql

  presenter:
    extends:
      file: presenter/docker-compose.override.yml
      service: frontend

  backend:
    extends:
      file: backend/docker-compose.override.yml
      service: backend

networks:
  external-net:
  internal-net:
    internal: true

volumes:
  db_vol: 
  frontend_node_modules:
  backend_node_modules:
