services:
  database:
    image: mariadb:10.5
    environment:
      - MARIADB_ALLOW_EMPTY_PASSWORD=1
      - MARIADB_ALLOW_EMPTY_ROOT_PASSWORD=1
      - MARIADB_USER=root
    ports:
      - 3306:3306
    volumes:
      - db_vol:/var/lib/mysql

  presenter:
    build:
      context: ./presenter
      target: production
    ports:
      - 3001:3000
    environment:
      - NODE_ENV=production

  frontend:
    build:
      context: ./frontend
      target: production
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=production

  admin:
    build:
      context: ./admin
      target: production
    ports:
      - 3002:3000
    environment:
      - NODE_ENV=production

  backend:
    build:
      context: ./backend
      target: production
    depends_on:
      - database
    ports:
      - 4000:4000
    environment:
      - DATABASE_URL=mysql://root:@database:3306/dreammall.earth
      - NODE_ENV=production

volumes:
  db_vol:
  frontend_node_modules:
  backend_node_modules:
