version: "3.4"

services:

  #########################################################
  ## MARIADB ##############################################
  #########################################################
  database:
    networks: 
      - internal-net
      - external-net
