include:
  - path:
    - ./authentik/docker-compose.yml
    - ./authentik/docker-compose.test.yml

services:
  presenter:
    build:
      target: development
    ports:
      # development server port
      - 24678:24678
    environment:
      - NODE_ENV=development
    volumes:
      - ./presenter:/app

  presenter-storybook:
    build:
      context: ./presenter
      target: storybook
    ports:
      - 6006:6006
    environment:
      - NODE_ENV=development
    volumes:
      - ./presenter:/app

  frontend:
    build:
      target: development
    ports:
      # development server port
      - 24679:24679
    environment:
      - NODE_ENV=development
      - PORT_HMR=24679
    volumes:
      - ./frontend:/app

  frontend-storybook:
    build:
      context: ./frontend
      target: storybook
    ports:
      - 6007:6006
    environment:
      - NODE_ENV=development
    volumes:
      - ./frontend:/app

  admin:
    build:
      target: development
    ports:
      # development server port
      - 24680:24680
    environment:
      - NODE_ENV=development
      - PORT_HMR=24680
    volumes:
      - ./admin:/app

  admin-storybook:
    build:
      context: ./admin
      target: storybook
    ports:
      - 6008:6006
    environment:
      - NODE_ENV=development
    volumes:
      - ./admin:/app

  backend:
    build:
      context: ./backend
      target: development
    environment:
      - NODE_ENV=development
    volumes:
      - ./backend:/server

  documentation:
    build:
      target: documentation
    ports:
      - 8080:8080
    environment:
      - NODE_ENV=development
    volumes:
      - ./:/app
