secrets:
    acme_email: ENC[AES256_GCM,data:TZrjQmThJHc6THdiob4g81yg,iv:xaTSwvTEId9z7YOzJkcClku7uFwhYK4MsDIbXe5+tgM=,tag:LuF+jS29OFiOtkYumUQHvg==,type:str]
    backend:
        env:
            DATABASE_URL: ENC[AES256_GCM,data:0xAIFTMMmgOoJqHFGq1PmnVQaX6t31LqIe6HD3qymTgtFmQ8aUyKHsWcZ1MgA6i5AVPTF1oGI6Sr32EMpOcEXWAHF+drdvlFegWIcp8qzeo=,iv:9IzLgfUZWeWBPh6NLadpmtNRg0FPJcKw3ey7D8MbcMk=,tag:ZfotHPuA9lcqkFex9CNFnw==,type:str]
            BBB_SHARED_SECRET: ENC[AES256_GCM,data:PSrXwBVvU9EBCdIBK+bKNmxKhPHjvc/GTikx1HPdeFnYIUrD3iq67w==,iv:urwqilLVfkiv/taWQVdZ9XFkVxVrd05dI67+LHhAbto=,tag:cOwtNyeY4HzxUXynEPOIzw==,type:str]
            WEBHOOK_SECRET: ENC[AES256_GCM,data:Y7yU1eWoDFb5Ch1Jj7Zo8aJDvpiTGF5NkK8QDFe4Ztt1uETMwUf4UdzZhuKR11O/wdNyP5JxdIgMLlJTxw1BEA==,iv:eRyuyzxURrA6LC8jV/dRA5m17OO/OUz8A307lRKfwl4=,tag:JkqYZLSEo6CqDMUVtcr7SQ==,type:str]
            BREVO_KEY: ENC[AES256_GCM,data:VXmXBia9eYhd2MUc5VmtnbWdJ7k2mCDJxpTBpGl47xqBCzteXXzNdpDlq5wCDpzYxJFxBKLjehqMLNmXSjghW5fnzmfN8ho3KK3RR6Jhrk5AplaCay0gwNc=,iv:EZ/Qiju9jZUcE9xRmD+3s1lG+DEoqXeajQ6VawN4xoI=,tag:DUkyqHNUGcMmLpH1jZUouA==,type:str]
            BREVO_ADMIN_NAME: ENC[AES256_GCM,data:5Eodz4E1hlSPsu/YsyDq7Nc=,iv:dxwacji9In7As3eFtDNbVhiMtvIzRCJZJjObjDpZqAw=,tag:AV3CRO2NPXxGYnEm7ABWXw==,type:str]
            BREVO_ADMIN_EMAIL: ENC[AES256_GCM,data:AQJcj0dB7JCN9BuK9UOI12N73BACjXo=,iv:zhyWgNxnoZZAmWzIRDum4gPCPMurvTJpaD5ONQ8oRPU=,tag:sMBYvMsywdGErGhGt3KZtA==,type:str]
            BREVO_CONTACT_TEMPLATE_ADMIN: ENC[AES256_GCM,data:olA=,iv:Qj2ucrby8URZ1SI4CEi561/7+6Ceisfbr2rkJUX9tk4=,tag:Ubv7NfoRrqUxQmCnzzXA1w==,type:str]
            BREVO_CONTACT_TEMPLATE_USER: ENC[AES256_GCM,data:yg==,iv:eGkkplWHVhG7br9o5FgbQzC3cJg6BwhyRTb9Q/5pM1s=,tag:eTj9eTuwn/qzQxEakEQc7Q==,type:str]
            BREVO_NEWSLETTER_TEMPLATE_OPTIN: ENC[AES256_GCM,data:LbY=,iv:gnJuxVnSQun+un6YBZjHb7Odwii+dJMoWhrr+ZMkfhk=,tag:uVtJ4CJxzZ7FZ8N3pAHCYQ==,type:str]
            BREVO_NEWSLETTER_LIST: ENC[AES256_GCM,data:Tg==,iv:zxdZnonFX7KkbiTBSnVAaJD+RD9nsjQ6fHBeElA3GgU=,tag:1ZDfy0M6brk8t4uS4NIGlw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1al36hkk8can83zpxq8qyy07gpv83hdw9vchfly5f264kanz405as283a00
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLdGIraTVmSzZsL1pJZ29N
            Ky94aWE3NnpZUkpmaDI4QVVFUGs4T2tkWDBBCmxDcVlaMis3MDY1WWFZNm1nZXFG
            c0tQNDlkb0tDeUlHdHFDSkpMMGIwUVEKLS0tIGQzZXE4cnJBSnBUd1hGM1QxZEN0
            T3NqU0c2ZHI1UWhsREdyeERpQlkzQU0KXYd3gPTMFlJWvc9kuTHs1WAMsMqdzVob
            R2tI4RZXotmeRYVmMFTYRLaNkCIgMv+HcFuqcoI26pmHsIyUcdCM5Q==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1llp6k66265q3rzqemxpnq0x3562u20989vcjf65fl9s3hjhgcscq6mhnjw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuY1NZOTFxOXBVQWRncmZ3
            YlZ5dm1IbzFvUVN1Qm5YaVdmQnhVNzVWejFzCnZTZTRKZWdONldUcXFrMjhqK0pI
            c3dCUHIvdWEwUUdTNWl6MVFPSFZOMWMKLS0tICsyNmJ2TzBOa1IzT0NseVNVTHhv
            d0ltb3NpdEJzK2M2cDlON0E5cmVvNDAKvCR1lmmv81zv7a0ym1brvLJJ2UJqlBw3
            DdPtgzDxe/qLq9Qe8W32xcmoExpdZKCWNdvYZZ1fQHDW0FGQOvyJRw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1zycwtk6dkxj6vuqhj9jw7932ythky9p3att6df4z9qasyw8v5dxquejcmp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwTkRkNG14L3lEYXlIa0s3
            MnhabnJGcVhxblA5aS9xYUVuWmNINVRyRVJJCno5TTRxT2wrQWxGNmVxaU9tSThD
            dWp3Mmd5QkJzcHNqWVV0ZHN2eDRqL1UKLS0tIFFONlBqKzBwc092RVNNQkdwcXo2
            OFlqUzJ1SUQxNDFVR1kxMGMwYitCbWsKo29Xf0S93oxPzHcCsRVR675oa82180QH
            QOmgr4W1RNuVmTTISUQkyHp0J/X5cMaxjmC65KYchv8lnSkuAFNTUA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1t0ufylv5xfwhmcamu4gpwtay4wcuyqgzlkht4t04s9qjl8xjks9skxrt02
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzZUovUWtCdjg3K3pGcFow
            K3NRSHQ2aXB4QnRRckljRTJaMnpRN1ZGQVhZCnlISEpIWFBCZko0cDlwUU5QUy8r
            MTM4RUNpUjNNRGFSR0RZR2hZYldXeUkKLS0tIEJvVHQzOC83bzg2MXNheGxKeDk3
            V0loN2c5b3d1VWhGRXNraTZES3NaOW8KKJTs9itfIIvY0j5S8gIQrAbUZhwMycwo
            rvLArikqcyNhmH5/pdWFv/c6YnhGf01pTxL0+h7ze6Rk2TOSB+IDlw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age15g5mhkcrseuxq923j7vdnmrzq4eh08ujha864k8hc6ncrj5sqfcsqkkyr2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTc3dwVmlGZVhRVWpISXlW
            dWlZMnFsLzBneFJESVk2YnVlYnlQQjVlVVJJCjdOYzN6Ym5jbGtzRG9BRTVwYzlG
            U3JSd2tXNitmMlUxMGNxd0JQWko2bHMKLS0tIGJJaGZyeFg5c3VkenEwcG90UzNJ
            MDQwU01qcjJCYTBNMTJKN2UrcVN1L2sKg4/mfOVrnqQgXFutcA3SpWAeNUkXd0Jk
            T6Euip50XQcIkHwlol3G0TpDcCfxjRnMh6p8QzR+i/276DI8yDn1OA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age15arcg8x6ltnsacwalvny0h2d4d4wkdmax328mw3v5vda9zm97uqshtavmr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzK1E0emtkSDRDK2Z3WVNx
            WFJlUDBGc096eVVFMDZYZjh5K0IxK3prWGdzCmE4b0NqeG5XalVpcmJzU1lGQ1oz
            NHo0aEk0SlRJTHNrWGgrb20yZkVQN2sKLS0tIDdJMUI4VHJtQ2N5R3I1VmNWSkZn
            bCsvYTJsUE5LU210NXdtcmJiYVdhaDAKWSK19OeYPh2NU5ii2NjJkUqS6i1dL1Rg
            7el4G6hlQ8ZGaqUjVIfArNjB7rMqSt3TPeodK/VpexLFH5xGzOk0Nw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1khw2eps099audp3uu5s9rk07qznllh5c8a43gv5dtpnq2a7lue6qrehn5s
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTMGMvSTlyOENnd1lYb3d2
            K3NGMFVnTiswdDc0SHNQZ1MvaVNRbkhtSkhjClhrdlVvWi9vc2o1VHFDZGxXaEdC
            bFprUG53RkpXV29rMTJVeEM5ZVFnenMKLS0tIFpPQ0k1aVBOaCsybHMyL2x3SGs3
            NDM4dE1JeFpqSUI0blB3WlcvbTd2cGsKscgnS2kbnztvBu2moNQKFSwjB35mGDZP
            OrUjDCPSz1iehO4hX1yNgiJcix4ZSYFRcUAmeyXQfnNGhDxab5UB0w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-22T10:23:38Z"
    mac: ENC[AES256_GCM,data:54c0a17ysuTeXfWL56thrMxgKsMjGYv6HpiLXTT5RjnVQvYpM2CwqRxlMQF3N3nvRwy2MQm4aWC9ObYRlt8EBFQ00f7/jdGhC7Y/iLXNWYDiF1t+JUdo3MHSAvOPEp9l8F4L8HfoGfM6OrhwNuyj9QQNQPK9qZiWT5IK/3YJBS4=,iv:ydnrjz/RrSzYy8eibLknz1DX7prDS+vzBDAUh1Tdb2Y=,tag:KbQSBMzqgnwQbuG9sXPLiA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.0
