auth:
    username: ENC[AES256_GCM,data:8+ka8ouCLEnW,iv:0Nqu7b0iqyXe+87rDB9KaWBF8yRuKGiwtLQIVHOFrIA=,tag:O3XBCxOxKct7mUjd1UVe0Q==,type:str]
    database: ENC[AES256_GCM,data:P9Pej2qjEzjoJhX7dI5g,iv:mzSVSr2VazCgxiClOLoaSabbigktfJbgVXu0dzkK/Y0=,tag:2d8jhdpagsZO3/7Hk+daeA==,type:str]
    rootPassword: ENC[AES256_GCM,data:qhp+MkI7XVn0XgGtUzzkj6PRWE4eJdxOQzUHRyx5pFI=,iv:nH/hknb++F5NvHnMHHKiEuGfDYlixofqZLLP97TGnww=,tag:IGy7/2vZ3lUMAuu8czsJOA==,type:str]
    password: ENC[AES256_GCM,data:jw2d3FCu/mIqK7QRM0myzcOzmYSofSaK1JbvrW3ugHs=,iv:xiy8vN1NFq+kAqXouLLSwsPJKbh5zDwsJZGE8xYFar8=,tag:y75wTJaQnsHOKbnH8U665Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1llp6k66265q3rzqemxpnq0x3562u20989vcjf65fl9s3hjhgcscq6mhnjw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5QzNiVTBZQ0tVY2RFNUgr
            WkE3UmRIczFGVS84VkwybnV6ZVRUdlVCVlE4CnFSUWlEaExPcFpMWmVlMUtEZmZF
            S2NCV1Avd3NPckxnRjh4UG4wdnlmNDAKLS0tIFJDcHBLL0ZFOGk0dVQva1M0cEl6
            Wk8zVUFZR2xzZlI3TXNhbk4rWTVkNkUKbmNUBuR41pdFPcLalEnIEEPbIUR6sdgv
            DXOOA27nUltmcZOfleO7QdrmtpR58yB+I0x2xgGvNmg3n1roIGGV1Q==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1zycwtk6dkxj6vuqhj9jw7932ythky9p3att6df4z9qasyw8v5dxquejcmp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4bzI2Y1BWMStIVGdjbG9z
            dkdiQkpmNHJqcGtpamI1M28zL3hSUU91dXhRClFUNThtYkJGZFAxY1o1QzVRT1lR
            VCtjWDMzMXF4eFY4cWVXakdmMEd5SmsKLS0tIDF3Zm9Gckxzd3haRzZVeVJLV1ZP
            b1BiMzVQNDEvcDAyZVZKR29hMTNMQ0EKOZjl9f8OFZN9h4f2Z4DlexxAF8hMixgm
            IWC+gaD9tAh/fIjN9fcB+h4sixc/t65v20VN6WQBegG7CsGuqeyP1Q==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1t0ufylv5xfwhmcamu4gpwtay4wcuyqgzlkht4t04s9qjl8xjks9skxrt02
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzTFRYU1V6ZlFtRG12Zi9x
            ckxvUTFSN2RObjQzQ09WV21yWlB5RUxWeGpZCjEvMXZIbC82amRGWC9GalRKc3Bk
            ak5mcG5FVWpIN2hZYXdRMVE0TXZ6eEkKLS0tIDgrRFQrZmhLSWRqZ1Q0U2ZvTDd6
            aFNxSDhhMit6S0F3bGU2RmM0ZU5Tbm8K19VzBqYYOZwS/UsmPquXSCII/h1MoeKt
            3I+lZIvdZJTJF24jq9lWmLHM5aEZZd2plJXhtN49nlF3yThbXcLIJA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-01T15:19:54Z"
    mac: ENC[AES256_GCM,data:JXQidrSRvs2ZjVj79CiSSoscU4Xx1/GhfIC4WGz8uGmmAiUi2chD+MoafpGFJSlJoLeU05lbwkMnpYRkyeNhTKelyEAOxlewCFb3ysUbStHSrvNXPM0hEddoxYA6B3pciwiL8yH3PaiVhxIyRd7XQAPTdKcqyRVisZjoxI0O0Bs=,iv:m6X4veK/d/DypXVwNBDbx5Ce8fdc36Ew2eoWhfh20AI=,tag:RkA2FKxNiz8qjaX8h30meg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.0
