auth:
    username: ENC[AES256_GCM,data:8+ka8ouCLEnW,iv:0Nqu7b0iqyXe+87rDB9KaWBF8yRuKGiwtLQIVHOFrIA=,tag:O3XBCxOxKct7mUjd1UVe0Q==,type:str]
    database: ENC[AES256_GCM,data:P9Pej2qjEzjoJhX7dI5g,iv:mzSVSr2VazCgxiClOLoaSabbigktfJbgVXu0dzkK/Y0=,tag:2d8jhdpagsZO3/7Hk+daeA==,type:str]
    rootPassword: ENC[AES256_GCM,data:qhp+MkI7XVn0XgGtUzzkj6PRWE4eJdxOQzUHRyx5pFI=,iv:nH/hknb++F5NvHnMHHKiEuGfDYlixofqZLLP97TGnww=,tag:IGy7/2vZ3lUMAuu8czsJOA==,type:str]
    password: ENC[AES256_GCM,data:jw2d3FCu/mIqK7QRM0myzcOzmYSofSaK1JbvrW3ugHs=,iv:xiy8vN1NFq+kAqXouLLSwsPJKbh5zDwsJZGE8xYFar8=,tag:y75wTJaQnsHOKbnH8U665Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1llp6k66265q3rzqemxpnq0x3562u20989vcjf65fl9s3hjhgcscq6mhnjw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIMUtjTUcxS2pZSStLUDJ5
            eUFuWUsyb2NGNlRNanRsZHU2QlVoZU9wYmdRCkRPUjZBVjJnSG1SeFpXUFJQaVFv
            UVRQajJWVkRjRE0rMHZVY0xPTDBWWkEKLS0tIHdBakFFZVJFQ2hhT2NOMW1sL2FT
            R0Z6MkU5MlZuMTBzb1lDUW1ja01oYW8KCWSEiN5E0Sy8AHZKcGgoJFsexrwWoOkh
            PLRF/VrvORsTpbxDY57jtHiTSUZs3wnlaL0p4sq42bVHQjQBQocJog==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1zycwtk6dkxj6vuqhj9jw7932ythky9p3att6df4z9qasyw8v5dxquejcmp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrUXVCRzdOUXZYNEJFTGZi
            bDR1YnpzN016Y09leTZLc2pUWnFoWUtHNEZVCkxmdkxNOTlvT082dThmdXpQYm1I
            eU1jSk50TzVlVDc2QnpKVXBpWVQ0ZUUKLS0tIDdoVmJIK3M0bWpQVHMrUkg1Mytv
            bWtadGVwc1EyQy9nYzNXaVZIVzIydzgKkl5gyny+PdxHRrux6X3FEaggwhaWOpQp
            TJkK74PTk5K28Ab0caBBOGgamdPdm/YoRNlBks66MUSXJHLJa5tqag==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1t0ufylv5xfwhmcamu4gpwtay4wcuyqgzlkht4t04s9qjl8xjks9skxrt02
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDODRSUDVtR0tnWEZwWlV4
            bEpBeUtUNzBtNDduSGpiM0Rvek9nY3BLY3lZCmZuSTZTZ0R2OFdSWUNobHBDanBw
            aHkrcVJtdTZ0RDBubStwSVYyOWlrbncKLS0tIG90Nld3cFJJTHFjOXhDRHVrTzg5
            cCtYU1M4OXdmUE1YckVMUkFMem1jaGcKjxhAG+olqHI/cv54h1nyHCrxvipSLpN6
            GguqxF7H6drZpA/0+uZBLsdVFVqJQIveB3C/HOiP2RmkJkRgMwPB6g==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age15g5mhkcrseuxq923j7vdnmrzq4eh08ujha864k8hc6ncrj5sqfcsqkkyr2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoL3RydFFqZjFrSE1scmZl
            TkxMMXU5Zm9PclIyRXFqem1FNDcydjRmeHlNCmk0WDArSDB3Qml4SVVCWHlqN09W
            S1NwYzlzL2ZUcEtCdjZWZyt2M0NybHcKLS0tIDNFOUVINTlnNDdJcFpxYlZiUE43
            azdCNG83N3NGa29YcGNpSlpmbnBBVVUKY2EKJIUOojT5/4OzGA5otsvDohFvy5Nn
            /hf1LEIKTZ1OHef6VTC7rS53ygLkcSxCHm8zKwfIVCPfNgP2r6jQ8g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-01T15:19:54Z"
    mac: ENC[AES256_GCM,data:JXQidrSRvs2ZjVj79CiSSoscU4Xx1/GhfIC4WGz8uGmmAiUi2chD+MoafpGFJSlJoLeU05lbwkMnpYRkyeNhTKelyEAOxlewCFb3ysUbStHSrvNXPM0hEddoxYA6B3pciwiL8yH3PaiVhxIyRd7XQAPTdKcqyRVisZjoxI0O0Bs=,iv:m6X4veK/d/DypXVwNBDbx5Ce8fdc36Ew2eoWhfh20AI=,tag:RkA2FKxNiz8qjaX8h30meg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.0
