apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f ../../docker-compose.yml -o dreammall/templates/
    kompose.version: 1.32.0 (HEAD)
  labels:
    io.kompose.service: admin
  name: admin
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: admin
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f ../../docker-compose.yml -o dreammall/templates/
        kompose.version: 1.32.0 (HEAD)
      labels:
        io.kompose.network/dreammallearth-default: "true"
        io.kompose.service: admin
    spec:
      containers:
        - env:
            - name: NODE_ENV
              value: production
            - name: PUBLIC_ENV__META__BASE_URL
              value: "https://admin.{{ .Values.dreammall.domain }}/"
              {{- range $key, $val := .Values.dreammall.admin.environment }}
            - name: {{ $key }}
              value: {{ $val | quote }}
              {{- end }}
          image: "{{ .Values.dreammall.admin.image.repository }}:{{ .Values.global.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.global.image.pullPolicy }}
          name: admin
          ports:
            - containerPort: 3000
              hostPort: 3002
              protocol: TCP
      restartPolicy: Always
