apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f ../../docker-compose.yml -o dreammall/templates/
    kompose.version: 1.32.0 (HEAD)
  labels:
    io.kompose.service: admin
  name: admin
spec:
  ports:
    - name: "3002"
      port: 3002
      targetPort: 3000
  selector:
    io.kompose.service: admin
