export enum EventType {
  CONTACTFORM_SEND = 'CONTACTFORM_SEND',
  NEWSLETTER_CONFIRM = 'NEWSLETTER_CONFIRM',
  NEWSLETTER_SUBSCRIBE = 'NEWSLETTER_SUBSCRIBE',
  CREATE_USER = 'CREATE_USER',
  CREATE_MY_TABLE = 'CREATE_MY_TABLE',
  UPDATE_MY_TABLE = 'UPDATE_MY_TABLE',
}
