global:
  image:
    pullPolicy: Always
    tag: master
frontend:
  image:
    repository:  ghcr.io/dreammall-earth/dreammall.earth/frontend
presenter:
  image:
    repository: ghcr.io/dreammall-earth/dreammall.earth/presenter
backend:
  image:
    repository:  ghcr.io/dreammall-earth/dreammall.earth/backend

cert_manager:
  issuer:

hosts:
  frontend: app.master.dreammall.earth
  presenter: master.dreammall.earth

configmap:
  auth_authority_url: https://auth.master.dreammall.earth/application/o/dreammallearth/
  auth_redirect_uri: https://app.master.dreammall.earth/auth/
  auth_signout_uri: https://auth.master.dreammall.earth/if/flow/dreammallearth-invalidation-flow/
  auth_signup_uri: https://auth.master.dreammall.earth/if/flow/dreammallearth-enrollment/
  auth_silent_redirect_uri: https://app.master.dreammall.earth/silent-refresh/
  bbb_url: https://cafe.dreammall.earth/bigbluebutton/api/
  bbb_webhook_url: https://master.dreammall.earth/api/bbb-webhook
  endpoints_graphql_uri: https://master.dreammall.earth/api/
  endpoints_websocket_uri: ws://master.dreammall.earth/api/subscriptions
  frontend_url:  https://app.master.dreammall.earth
  frontend_signin_url:  https://app.master.dreammall.earth/signin
  jwks_uri: http://authentik-server/application/o/dreammallearth/jwks/
  presenter_url: https://master.dreammall.earth
  account_holder: 'DreamMall Verlag GbR Claudia Siebert und Sabine Laudien'
  account_holder_address: 'Rosenau 15, DE-87437 Kempten'
  iban: 'DE667 333170000 10000 504'
  bic: 'GABLDE71XXX'
  bank: 'Gabler-Saliter Bank'
  sentry_dsn: 'https://1f94061db34f923d76b8eb85ccb132f8@o4508075566956544.ingest.de.sentry.io/4508075570561104'
  sentry_environment: ''
