domain: dreammall.earth

global:
  image:
    pullPolicy: Always
    tag: master

frontend:
  image:
    repository:  ghcr.io/dreammall-earth/dreammall.earth/frontend
  env:
    UMAMI_WEBSITE_ID: 848016ec-3c22-403c-86be-9b21864d1256
    SENTRY_DSN: https://a8ad24bf9db4356ad721fe8974c058f0@o4508075566956544.ingest.de.sentry.io/4508076485509200
    PUBLIC_ENV__ACCOUNT_HOLDER: 'DreamMall Verlag GbR Claudia Siebert und Sabine Laudien'
    PUBLIC_ENV__ACCOUNT_HOLDER_ADDRESS: 'Rosenau 15, DE-87437 Kempten'
    PUBLIC_ENV__IBAN: 'DE667 333170000 10000 504'
    PUBLIC_ENV__BIC: 'GABLDE71XXX'
    PUBLIC_ENV__BANK: 'Gabler-Saliter Bank'

presenter:
  image:
    repository: ghcr.io/dreammall-earth/dreammall.earth/presenter
  env:
    UMAMI_WEBSITE_ID: 210f7ce8-f8a0-4adb-be35-bf54ae5c93aa
    SENTRY_DSN: https://ee21d8029a7c481e7e0835fc8e6421d6@o4508075566956544.ingest.de.sentry.io/4508076577521744

backend:
  image:
    repository:  ghcr.io/dreammall-earth/dreammall.earth/backend
  env:
    BBB_URL: https://cafe.dreammall.earth/bigbluebutton/api/
    SENTRY_DSN: https://1f94061db34f923d76b8eb85ccb132f8@o4508075566956544.ingest.de.sentry.io/4508075570561104

cert_manager:
  issuer:
