const VALIDATION = {
  MAX_CHARS_FIRST_NAME: 50,
  MAX_CHARS_LAST_NAME: 50,
  MAX_CHARS_EMAIL: 254,
  MAX_CHARS_CONTENT: 255,
  MAX_CHARS_NAME: 254,
  MAX_CHARS_INTRODUCTION: 25,
  MAX_CHARS_USER_DETAIL_TEXT: 40,
}

export { VALIDATION }
