apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: backend
  template:
    metadata:
      labels:
        io.kompose.service: backend
    spec:
      restartPolicy: Always
      initContainers:
        - env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}
                  key: database_url
            - name: FRONTEND_URL
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}
                  key: frontend_url
            - name: FRONTEND_INVITE_LINK_URL
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}
                  key: frontend_invite_link_url
            - name: NODE_ENV
              value: production
          image: "{{ .Values.backend.image.repository }}:{{ default .Values.global.image.tag .Values.backend.image.tag "latest" }}"
          imagePullPolicy: {{ quote .Values.global.image.pullPolicy }}
          name: backend-migrations
          command: [ 'npm', 'run', 'db:migrate:deploy' ]
      containers:
        - env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}
                  key: database_url
            - name: FRONTEND_URL
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}
                  key: frontend_url
            - name: FRONTEND_INVITE_LINK_URL
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}
                  key: frontend_invite_link_url
            - name: JWKS_URI
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}
                  key: jwks_uri
            - name: BBB_URL
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}
                  key: bbb_url
            - name: BBB_SHARED_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}
                  key: bbb_shared_secret
            - name: NODE_ENV
              value: production
            - name: BREVO_KEY
              value: ""
            - name: BREVO_ADMIN_NAME
              value: ""
            - name: BREVO_ADMIN_EMAIL
              value: ""
            - name: BREVO_CONTACT_TEMPLATE_ADMIN
              value: "1"
            - name: BREVO_CONTACT_TEMPLATE_USER
              value: "2"
            - name: BREVO_NEWSLETTER_TEMPLATE_OPTIN
              value: "3"
            - name: BREVO_NEWSLETTER_LIST
              value: "3"
          image: "{{ .Values.backend.image.repository }}:{{ default .Values.global.image.tag .Values.backend.image.tag "latest" }}"
          imagePullPolicy: {{ quote .Values.global.image.pullPolicy }}
          name: backend
          ports:
            - containerPort: 4000
