apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: backend
  template:
    metadata:
      labels:
        io.kompose.service: backend
    spec:
      restartPolicy: Always
      initContainers:
        - name: backend-migrations
          image: "{{ .Values.backend.image.repository }}:{{ default .Values.global.image.tag .Values.backend.image.tag "latest" }}"
          imagePullPolicy: {{ quote .Values.global.image.pullPolicy }}
          command: [ 'npm', 'run', 'db:migrate:deploy' ]
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}
                  key: database_url
            - name: FRONTEND_URL
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}
                  key: frontend_url
            - name: NODE_ENV
              value: production
      containers:
        - name: backend
          image: "{{ .Values.backend.image.repository }}:{{ default .Values.global.image.tag .Values.backend.image.tag "latest" }}"
          imagePullPolicy: {{ quote .Values.global.image.pullPolicy }}
          ports:
            - containerPort: 4000
          envFrom:
            - secretRef:
                name: {{ .Release.Name }}-backend-env
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}
                  key: database_url
            - name: FRONTEND_URL
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}
                  key: frontend_url
            - name: JWKS_URI
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}
                  key: jwks_uri
            - name: BBB_URL
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}
                  key: bbb_url
            - name: BBB_SHARED_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}
                  key: bbb_shared_secret
            - name: BBB_WEBHOOK_URL
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}
                  key: bbb_webhook_url
            - name: SENTRY_DSN
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}
                  key: sentry_dsn_backend
            - name: SENTRY_ENVIRONMENT
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}
                  key: sentry_environment
            - name: WEBHOOK_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}
                  key: webhook_secret
            - name: NODE_ENV
              value: production
