apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: backend
  template:
    metadata:
      labels:
        io.kompose.service: backend
    spec:
      restartPolicy: Always
      initContainers:
        - name: backend-migrations
          image: "{{ .Values.backend.image.repository }}:{{ default .Values.global.image.tag .Values.backend.image.tag "latest" }}"
          imagePullPolicy: {{ quote .Values.global.image.pullPolicy }}
          command: [ 'npm', 'run', 'db:migrate:deploy' ]
          envFrom:
            - secretRef:
                name: {{ .Release.Name }}-backend-env
      containers:
        - name: backend
          image: "{{ .Values.backend.image.repository }}:{{ default .Values.global.image.tag .Values.backend.image.tag "latest" }}"
          imagePullPolicy: {{ quote .Values.global.image.pullPolicy }}
          ports:
            - containerPort: 4000
          envFrom:
            - configMapRef:
                name: {{ .Release.Name }}-backend-env
            - secretRef:
                name: {{ .Release.Name }}-backend-env
          env:
            - name: JWKS_URI
              value: http://authentik-server/application/o/dreammallearth/jwks/
            - name: SENTRY_ENVIRONMENT
              value: {{ .Values.domain }}
            - name: FRONTEND_URL
              value: https://app.{{ .Values.domain }}
            - name: BBB_WEBHOOK_URL
              value: https://{{ .Values.domain }}/api/bbb-webhook
