apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: frontend
  template:
    metadata:
      labels:
        io.kompose.service: frontend
    spec:
      containers:
        - name: frontend
          image: "{{ .Values.frontend.image.repository }}:{{ default .Values.global.image.tag .Values.frontend.image.tag "latest" }}"
          imagePullPolicy: {{ quote .Values.global.image.pullPolicy }}
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: {{ .Release.Name }}-frontend-env
          env:
            - name: PUBLIC_ENV__AUTH__AUTHORITY
              value: https://auth.{{ .Values.domain }}/application/o/dreammallearth/
            - name: PUBLIC_ENV__AUTH__AUTHORITY_SIGNUP_URI
              value: https://auth.{{ .Values.domain }}/if/flow/dreammallearth-enrollment/
            - name: PUBLIC_ENV__AUTH__AUTHORITY_SIGNOUT_URI
              value: https://auth.{{ .Values.domain }}/if/flow/dreammallearth-invalidation-flow/
            - name: PUBLIC_ENV__AUTH__REDIRECT_URI
              value: https://app.{{ .Values.domain }}/auth/
            - name: PUBLIC_ENV__AUTH__SILENT_REDIRECT_URI
              value: https://app.{{ .Values.domain }}/silent-refresh/
            - name: PUBLIC_ENV__ENDPOINTS__GRAPHQL_URI
              value: https://{{ .Values.domain }}/api/
            - name: PUBLIC_ENV__ENDPOINTS__WEBSOCKET_URI
              value: wss://{{ .Values.domain }}/api/subscriptions
            - name: PUBLIC_ENV__META__BASE_URL
              value: https://app.{{ .Values.domain }}
            - name: SENTRY_ENVIRONMENT
              value: {{ .Values.domain }}
      restartPolicy: Always
