---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}
  annotations:
    cert-manager.io/issuer: {{ .Values.cert_manager.issuer | default (printf "%s-letsencrypt-staging"  .Release.Name) }}
spec:
  tls:
  - hosts:
      - {{ quote .Values.hosts.frontend }}
      - {{ quote .Values.hosts.admin }}
      - {{ quote .Values.hosts.presenter }}
    secretName: {{ .Release.Name }}-letsencrypt-tls

  rules:
  - host: {{ quote .Values.hosts.frontend }}
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: {{ .Release.Name }}-frontend
              port:
                number: 3000

  - host: {{ quote .Values.hosts.admin }}
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: {{ .Release.Name }}-admin
              port:
                number: 3002

  - host: {{ quote .Values.hosts.presenter }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ .Release.Name }}-presenter
            port:
              number: 3001

---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: {{ .Release.Name }}-stripprefix
spec:
  stripPrefix:
    prefixes:
      - /api

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-path-prefixes
  annotations:
    traefik.ingress.kubernetes.io/router.middlewares: "{{ .Release.Namespace }}-{{ .Release.Name }}-stripprefix@kubernetescrd"
spec:
  rules:
  - host: {{ quote .Values.hosts.presenter }}
    http:
      paths:
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: {{ .Release.Name }}-backend
            port:
              number: 4000
