apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-presenter
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: presenter
  template:
    metadata:
      labels:
        io.kompose.service: presenter
    spec:
      containers:
        - name: presenter
          image: "{{ .Values.presenter.image.repository }}:{{ default .Values.global.image.tag .Values.presenter.image.tag "latest" }}"
          imagePullPolicy: {{ quote .Values.global.image.pullPolicy }}
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: {{ .Release.Name }}-presenter-env
          env:
            - name: PUBLIC_ENV__SIGNUP_URI
              value: https://auth.{{ .Values.domain }}/if/flow/dreammallearth-enrollment/
            - name: PUBLIC_ENV__SIGNIN_URI
              value: https://app.{{ .Values.domain }}/signin
            - name: PUBLIC_ENV__ENDPOINTS__GRAPHQL_URI
              value: https://{{ .Values.domain }}/api/
            - name: SENTRY_ENVIRONMENT
              value: {{ .Values.domain }}
      restartPolicy: Always
