apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-presenter
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: presenter
  template:
    metadata:
      labels:
        io.kompose.service: presenter
    spec:
      containers:
        - env:
            - name: PUBLIC_ENV__SIGNUP_URI
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}
                  key: auth_signup_uri
            - name: PUBLIC_ENV__SIGNIN_URI
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}
                  key: frontend_signin_url
            - name: PUBLIC_ENV__ENDPOINTS__GRAPHQL_URI
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}
                  key: endpoints_graphql_uri
          image: "{{ .Values.presenter.image.repository }}:{{ default .Values.global.image.tag .Values.presenter.image.tag "latest" }}"
          imagePullPolicy: {{ quote .Values.global.image.pullPolicy }}
          name: presenter
          ports:
            - containerPort: 3000
      restartPolicy: Always
