apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-presenter
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: presenter
  template:
    metadata:
      labels:
        io.kompose.service: presenter
    spec:
      containers:
        - env:
          image: "{{ .Values.presenter.image.repository }}:{{ default .Values.global.image.tag .Values.presenter.image.tag "latest" }}"
          imagePullPolicy: {{ quote .Values.global.image.pullPolicy }}
          name: presenter
          ports:
            - containerPort: 3000
      restartPolicy: Always
