apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}
type: Opaque
stringData:
  authentik_bootstrap_password: {{ .Values.secrets.authentik_bootstrap_password | quote }}
  bbb_shared_secret: {{ .Values.secrets.bbb_shared_secret | quote }}
  database_url: {{ .Values.secrets.database_url | quote }}
