name: admin

on: [push,pull_request_target]

jobs:
  files-changed:
    name: Detect File Changes - admin/
    runs-on: ubuntu-latest
    outputs:
      admin: ${{ steps.filter.outputs.admin }}
      admin-docs: ${{ steps.filter.outputs.admin-docs }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3.0.2
        id: filter
        with:
          filters: |
            admin:
              - '.github/workflows/**/*'
              - 'admin/**/*'
            admin-docs:
              - '.github/workflows/**/*'
              - 'admin/**/*.md'
              - 'admin/.vuepress/*'
              - 'admin/package.json'

  build:
    if: needs.files-changed.outputs.admin == 'true'
    name: Build - Admin
    needs: files-changed
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: './.tool-versions'
          cache: 'pnpm'
      - run: pnpm install
      - name: Admin | Build
        run: pnpm run --filter dreammall-admin build

  docker-production:
    if: needs.files-changed.outputs.admin == 'true'
    name: Build Docker Production - Admin
    needs: files-changed
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Admin | Build Docker Production
        run: docker compose -f docker-compose.yml build admin

  docker-development:
    if: needs.files-changed.outputs.admin == 'true'
    name: Build Docker Development - Admin
    needs: files-changed
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Admin | Build Docker Development
        run: docker compose build admin admin-documentation admin-storybook

  docs:
    if: needs.files-changed.outputs.admin-docs == 'true'
    name: Build Docs - Admin
    needs: files-changed
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: './.tool-versions'
          cache: 'pnpm'
      - run: pnpm install
      - name: Admin | Build Docs
        run: pnpm run --filter dreammall-admin docs:build

  storybook:
    if: needs.files-changed.outputs.admin == 'true'
    name: Build Storybook - Admin
    needs: files-changed
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: './.tool-versions'
          cache: 'pnpm'
      - run: pnpm install
      - name: Admin | Build Storybook
        run: pnpm run --filter dreammall-admin storybook:build

  lint:
    if: needs.files-changed.outputs.admin == 'true'
    name: Lint - Admin
    needs: files-changed
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: './.tool-versions'
          cache: 'pnpm'
      - run: pnpm install
      - name: Admin | Lint
        run: pnpm run --filter dreammall-admin test:lint

  unit:
    if: needs.files-changed.outputs.admin == 'true'
    name: Unit - Admin
    needs: files-changed
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: './.tool-versions'
          cache: 'pnpm'
      - run: pnpm install
      - name: Admin | Unit
        run: pnpm run --filter dreammall-admin test:unit
