name: admin

on: push

jobs:
  files-changed:
    name: Detect File Changes - admin/
    runs-on: ubuntu-latest
    outputs:
      admin: ${{ steps.filter.outputs.admin }}
    steps:
      - uses: actions/checkout@9a9194f87191a7e9055e3e9b95b8cfb13023bb08 # v4.1.7
      - uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36 # v3.0.2
        id: filter
        with:
          filters: |
            admin:
              - '.github/workflows/**/*'
              - 'admin/**/*'

  build:
    if: needs.files-changed.outputs.admin == 'true'
    name: Build - Admin
    needs: files-changed
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9a9194f87191a7e9055e3e9b95b8cfb13023bb08 # v4.1.7
      - uses: actions/setup-node@26961cf329f22f6837d5f54c3efd76b480300ace # v4.0.3
        with:
          node-version-file: './.tool-versions'
      - name: Admin | Build
        run: npm install && npm run build
        working-directory: ./admin

  storybook:
    if: needs.files-changed.outputs.admin == 'true'
    name: Build Storybook - Admin
    needs: files-changed
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9a9194f87191a7e9055e3e9b95b8cfb13023bb08 # v4.1.7
      - uses: actions/setup-node@26961cf329f22f6837d5f54c3efd76b480300ace # v4.0.3
        with:
          node-version-file: './.tool-versions'
      - name: Admin | Build Storybook
        run: npm install && npm run storybook:build
        working-directory: ./admin

  lint:
    if: needs.files-changed.outputs.admin == 'true'
    name: Lint - Admin
    needs: files-changed
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9a9194f87191a7e9055e3e9b95b8cfb13023bb08 # v4.1.7
      - uses: actions/setup-node@26961cf329f22f6837d5f54c3efd76b480300ace # v4.0.3
        with:
          node-version-file: './.tool-versions'
      - name: Admin | Lint
        run: npm install && npm run test:lint
        working-directory: ./admin

  unit:
    if: needs.files-changed.outputs.admin == 'true'
    name: Unit - Admin
    needs: files-changed
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9a9194f87191a7e9055e3e9b95b8cfb13023bb08 # v4.1.7
      - uses: actions/setup-node@26961cf329f22f6837d5f54c3efd76b480300ace # v4.0.3
        with:
          node-version-file: './.tool-versions'
      - name: Admin | Unit
        run: npm install && npm run test:unit
        working-directory: ./admin
