name: "admin:deploy:chromatic"
on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    name: Chromatic - Admin
    runs-on: ubuntu-latest
    env:
      CHROMATIC_PROJECT_TOKEN: ${{ secrets.CHROMATIC_PROJECT_TOKEN_ADMIN }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version-file: './.tool-versions'
      - name: Admin | Build
        run: npm install && npm run chromatic -- --exit-zero-on-changes
        working-directory: ./admin
