name: "admin:test:build test code"

on: [push,pull_request_target]

jobs:
  # only (but most important) job from this workflow required for pull requests
  # check results serve as run conditions for all other jobs here
  files-changed:
    name: Detect File Changes - admin-test-build-code
    runs-on: ubuntu-latest
    outputs:
      changes: ${{ steps.changes.outputs.admin-test-build-code }}
    steps:
      - uses: actions/checkout@v4

      - name: Check for admin file changes
        uses: dorny/paths-filter@v3.0.2
        id: changes
        with:
          token: ${{ github.token }}
          filters: .github/file-filters.yml
          list-files: shell

  build:
    if: needs.files-changed.outputs.changes == 'true'
    name: Build - Admin
    needs: files-changed
    runs-on: ubuntu-latest
    env:
      WORKING_DIRECTORY: ./admin
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Admin | Build
        run: npm install && npm run build
        working-directory: ${{env.WORKING_DIRECTORY}}