name: backend

on: push

jobs:
  files-changed:
    name: Detect File Changes - backend/
    runs-on: ubuntu-latest
    outputs:
      backend: ${{ steps.filter.outputs.backend }}
    steps:
      - uses: actions/checkout@9a9194f87191a7e9055e3e9b95b8cfb13023bb08 # v4.1.7
      - uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36 # v3.0.2
        id: filter
        with:
          filters: |
            backend:
              - '.github/workflows/**/*'
              - 'backend/**/*'

  build:
    if: needs.files-changed.outputs.backend == 'true'
    name: Build - Backend
    needs: files-changed
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9a9194f87191a7e9055e3e9b95b8cfb13023bb08 # v4.1.7
      - uses: actions/setup-node@26961cf329f22f6837d5f54c3efd76b480300ace # v4.0.3
        with:
          node-version-file: './.tool-versions'
      - name: Backend | Build
        run: npm install && npm run build
        working-directory: ./backend

  docker-production:
    if: needs.files-changed.outputs.backend == 'true'
    name: Build Docker Production - Backend
    needs: files-changed
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9a9194f87191a7e9055e3e9b95b8cfb13023bb08 # v4.1.7
      - name: Backend | Build Docker Production
        run: docker compose -f docker-compose.yml build backend

  docker-development:
    if: needs.files-changed.outputs.backend == 'true'
    name: Build Docker Development - Backend
    needs: files-changed
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9a9194f87191a7e9055e3e9b95b8cfb13023bb08 # v4.1.7
      - name: Backend | Build Docker Development
        run: docker compose build backend

  lint:
    if: needs.files-changed.outputs.backend == 'true'
    name: Lint - Backend
    needs: files-changed
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9a9194f87191a7e9055e3e9b95b8cfb13023bb08 # v4.1.7
      - uses: actions/setup-node@26961cf329f22f6837d5f54c3efd76b480300ace # v4.0.3
        with:
          node-version-file: './.tool-versions'
      - name: Backend | Lint
        run: npm install && npm run test:lint
        working-directory: ./backend

  unit:
    if: needs.files-changed.outputs.backend == 'true'
    name: Unit - Backend
    needs: files-changed
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: mysql://root:@localhost:3306/dreammall.earth
    steps:
      - uses: actions/checkout@9a9194f87191a7e9055e3e9b95b8cfb13023bb08 # v4.1.7
      - uses: actions/setup-node@26961cf329f22f6837d5f54c3efd76b480300ace # v4.0.3
        with:
          node-version-file: './.tool-versions'
      - name: Backend | docker-compose database
        run: docker compose -f docker-compose.yml up --detach --no-deps database
      - name: Backend | Unit
        run: npm install && npm run db:migrate && npm run test:unit
        working-directory: ./backend
