name: backend

on: push

jobs:
  files-changed:
    name: Detect File Changes - backend/
    runs-on: ubuntu-latest
    outputs:
      backend: ${{ steps.filter.outputs.backend }}
    steps:
      - uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v4.1.7
      - uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36 # v3.0.2
        id: filter
        with:
          filters: |
            backend:
              - '.github/workflows/**/*'
              - 'backend/**/*'

  build:
    if: needs.files-changed.outputs.backend == 'true'
    name: Build - Backend
    needs: files-changed
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v4.1.7
      - uses: actions/setup-node@97ca147735c170fb35096b39ef17a0fc5d9270ac # v4.0.3
        with:
          node-version-file: './.tool-versions'
      - name: Backend | Build
        run: npm install && npm run build
        working-directory: ./backend

  lint:
    if: needs.files-changed.outputs.backend == 'true'
    name: Lint - Backend
    needs: files-changed
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v4.1.7
      - uses: actions/setup-node@97ca147735c170fb35096b39ef17a0fc5d9270ac # v4.0.3
        with:
          node-version-file: './.tool-versions'
      - name: Backend | Lint
        run: npm install && npm run test:lint
        working-directory: ./backend

  unit:
    if: needs.files-changed.outputs.backend == 'true'
    name: Unit - Backend
    needs: files-changed
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: mysql://root:@localhost:3306/dreammall.earth
    steps:
      - uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v4.1.7
      - uses: actions/setup-node@97ca147735c170fb35096b39ef17a0fc5d9270ac # v4.0.3
        with:
          node-version-file: './.tool-versions'
      - name: Backend | docker-compose database
        run: docker compose -f docker-compose.yml up --detach --no-deps database
      - name: Backend | Unit
        run: npm install && npm run db:migrate && npm run test:unit
        working-directory: ./backend
