name: "dreammall:deploy:docs to github"

on:
  push:
    branches:
      - master

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Set Node version
        uses: actions/setup-node@v4
        with:
          node-version: '>=21'

    - name: Checkout
      uses: actions/checkout@master

    - name: vuepress-deploy
      uses: jenkey2011/vuepress-deploy@master
      env:
        ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        #TARGET_REPO: username/repo
        #TARGET_BRANCH: master
        BUILD_SCRIPT: npm install && npm run docs:build
        BUILD_DIR: build/docs/
        VUEPRESS_BASE: "dreammall.earth"