name: "dreammall:deploy:docs to github"

on:
  push:
    branches:
      - master

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v4.1.7
      - uses: actions/setup-node@97ca147735c170fb35096b39ef17a0fc5d9270ac # v4.0.3
        with:
          node-version-file: './.tool-versions'
      - name: vuepress-deploy
        uses: IT4Change/vuepress-build-and-deploy@b7244880d4eecbdd2fc984e71b888f7eb5b2ba48 # v1.9.0
        env:
          ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          #TARGET_REPO: username/repo
          #TARGET_BRANCH: master
          BUILD_SCRIPT: npm install && npm run docs:build
          BUILD_DIR: build/docs/
          VUEPRESS_BASE: "dreammall.earth"
