name: "dreammall:deploy:docs to github"

on:
  push:
    branches:
      - master

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4.1.7
      - uses: actions/setup-node@0a44ba7841725637a19e28fa30b79a866c81b0a6 # v4.0.3
        with:
          node-version-file: './.tool-versions'
      - name: vuepress-deploy
        uses: IT4Change/vuepress-build-and-deploy@19811ceb94c74ca2b49def1b7afdfe27135276b8 # v1.9.0
        env:
          ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          #TARGET_REPO: username/repo
          #TARGET_BRANCH: master
          BUILD_SCRIPT: npm install && npm run docs:build
          BUILD_DIR: build/docs/
          VUEPRESS_BASE: "dreammall.earth"
