name: e2e:test:build test docs

on: [push,pull_request_target]

jobs:
  files-changed:
    name: Detect File Changes
    runs-on: ubuntu-latest
    outputs:
      changes: ${{ steps.changes.outputs.e2e-docs }}
    steps:
      - uses: actions/checkout@master

      - name: Check for e2e docs file changes
        uses: dorny/paths-filter@v3.0.2
        id: changes
        with:
          token: ${{ github.token }}
          filters: .github/file-filters.yml
          list-files: shell

  build:
    if: needs.files-changed.outputs.changes == 'true'
    name: Build Docs - E2E Testing
    needs: files-changed
    runs-on: ubuntu-latest
    env:
      WORKING_DIRECTORY: ./tests
    steps:
      - name: Set Node version
        uses: actions/setup-node@v4
        with:
          node-version: '>=21'

      - name: Checkout code
        uses: actions/checkout@master

      - name: E2E Testing | Build Docs
        run: npm install && npm run docs:build
        working-directory: ${{env.WORKING_DIRECTORY}}