name: e2e

on: push

jobs:
  files-changed:
    name: Detect File Changes - test/
    runs-on: ubuntu-latest
    outputs:
      e2e: ${{ steps.filter.outputs.e2e }}
    steps:
      - uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4.1.7
      - uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36 # v3.0.2
        id: filter
        with:
          filters: |
            e2e:
              - '.github/workflows/**/*'
              - 'tests/**/*'

  lint:
    if: needs.files-changed.outputs.e2e == 'true'
    name: Lint - E2E files
    needs: files-changed
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4.1.7

      - uses: actions/setup-node@0a44ba7841725637a19e28fa30b79a866c81b0a6 # v4.0.3
        with:
          node-version-file: './.tool-versions'

      - name: E2E files | Lint
        run: npm install && npm run test:lint
        working-directory: ./tests
