name: e2e:test:lint code with defined linters

on: push

jobs:
  files-changed:
    name: Detect File Changes
    runs-on: ubuntu-latest
    outputs:
      changes: ${{ steps.changes.outputs.e2e-all }}
    steps:
      - uses: actions/checkout@master

      - name: Check for frontend file changes
        uses: dorny/paths-filter@v3.0.2
        id: changes
        with:
          token: ${{ github.token }}
          filters: .github/file-filters.yml
          list-files: shell

  lint:
    if: needs.files-changed.outputs.changes == 'true'
    name: Lint - E2E files
    needs: files-changed
    runs-on: ubuntu-latest
    env:
      WORKING_DIRECTORY: ./cypress
    steps:
      - name: Set Node version
        uses: actions/setup-node@v4
        with:
          node-version: '>=21'

      - name: Checkout code
        uses: actions/checkout@master

      - name: E2E files | Lint
        run: npm install && npm run test:lint:eslint