name: e2e

on: push

jobs:
  files-changed:
    name: Detect File Changes - test/
    runs-on: ubuntu-latest
    outputs:
      e2e: ${{ steps.filter.outputs.e2e }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3.0.2
        id: filter
        with:
          filters: |
            e2e:
              - '.github/workflows/**/*'
              - 'tests/**/*'

  lint:
    if: needs.files-changed.outputs.e2e == 'true'
    name: Lint - E2E files
    needs: files-changed
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - uses: actions/setup-node@v4
        with:
          node-version-file: './.tool-versions'

      - name: E2E files | Lint
        run: npm install && npm run test:lint
        working-directory: ./tests
