name: frontend

on: push

jobs:
  files-changed:
    name: Detect File Changes - frontend/
    runs-on: ubuntu-latest
    outputs:
      frontend: ${{ steps.filter.outputs.frontend }}
    steps:
      - uses: actions/checkout@9a9194f87191a7e9055e3e9b95b8cfb13023bb08 # v4.1.7
      - uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36 # v3.0.2
        id: filter
        with:
          filters: |
            frontend:
              - '.github/workflows/**/*'
              - 'frontend/**/*'

  build:
    if: needs.files-changed.outputs.frontend == 'true'
    name: Build - Frontend
    needs: files-changed
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9a9194f87191a7e9055e3e9b95b8cfb13023bb08 # v4.1.7
      - uses: actions/setup-node@26961cf329f22f6837d5f54c3efd76b480300ace # v4.0.3
        with:
          node-version-file: './.tool-versions'
      - name: Frontend | Build
        run: npm install && npm run build
        working-directory: ./frontend

  docker-production:
    if: needs.files-changed.outputs.frontend == 'true'
    name: Build Docker Production - Frontend
    needs: files-changed
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9a9194f87191a7e9055e3e9b95b8cfb13023bb08 # v4.1.7
      - name: Frontend | Build Docker Production
        run: docker compose -f docker-compose.yml build frontend

  docker-development:
    if: needs.files-changed.outputs.frontend == 'true'
    name: Build Docker Development - Frontend
    needs: files-changed
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9a9194f87191a7e9055e3e9b95b8cfb13023bb08 # v4.1.7
      - name: Frontend | Build Docker Development
        run: docker compose build frontend frontend-storybook

  storybook:
    if: needs.files-changed.outputs.frontend == 'true'
    name: Build Storybook - Frontend
    needs: files-changed
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9a9194f87191a7e9055e3e9b95b8cfb13023bb08 # v4.1.7
      - uses: actions/setup-node@26961cf329f22f6837d5f54c3efd76b480300ace # v4.0.3
        with:
          node-version-file: './.tool-versions'
      - name: Frontend | Build Storybook
        run: npm install && npm run storybook:build
        working-directory: ./frontend

  lint:
    if: needs.files-changed.outputs.frontend == 'true'
    name: Lint - Frontend
    needs: files-changed
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9a9194f87191a7e9055e3e9b95b8cfb13023bb08 # v4.1.7
      - uses: actions/setup-node@26961cf329f22f6837d5f54c3efd76b480300ace # v4.0.3
        with:
          node-version-file: './.tool-versions'
      - name: Frontend | Lint
        run: npm install && npm run test:lint
        working-directory: ./frontend

  unit:
    if: needs.files-changed.outputs.frontend == 'true'
    name: Unit - Frontend
    needs: files-changed
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9a9194f87191a7e9055e3e9b95b8cfb13023bb08 # v4.1.7
      - uses: actions/setup-node@26961cf329f22f6837d5f54c3efd76b480300ace # v4.0.3
        with:
          node-version-file: './.tool-versions'
      - name: Frontend | Unit
        run: npm install && npm run test:unit
        working-directory: ./frontend
