name: "frontend:deploy:chromatic"
on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    name: Chromatic - Frontend
    runs-on: ubuntu-latest
    env:
      CHROMATIC_PROJECT_TOKEN: ${{ secrets.CHROMATIC_PROJECT_TOKEN_FRONTEND }}
    steps:
      - uses: actions/checkout@9a9194f87191a7e9055e3e9b95b8cfb13023bb08 # v4.1.7
        with:
          fetch-depth: 0
      - uses: actions/setup-node@26961cf329f22f6837d5f54c3efd76b480300ace # v4.0.3
        with:
          node-version-file: './.tool-versions'
      - name: Frontend | Build
        run: npm install && npm run chromatic -- --exit-zero-on-changes
        working-directory: ./frontend
