name: frontend

on: push

jobs:
  files-changed:
    name: Detect File Changes - frontend/
    runs-on: ubuntu-latest
    outputs:
      frontend: ${{ steps.filter.outputs.frontend }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3.0.2
        id: filter
        with:
          filters: |
            frontend:
              - '.github/workflows/**/*'
              - 'frontend/**/*'

  build:
    if: needs.files-changed.outputs.frontend == 'true'
    name: Build - Frontend
    needs: files-changed
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: './.tool-versions'
      - name: Frontend | Build
        run: npm install && npm run build
        working-directory: ./frontend

  storybook:
    if: needs.files-changed.outputs.frontend == 'true'
    name: Build Storybook - Frontend
    needs: files-changed
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: './.tool-versions'
      - name: Frontend | Build Storybook
        run: npm install && npm run storybook:build
        working-directory: ./frontend

  lint:
    if: needs.files-changed.outputs.frontend == 'true'
    name: Lint - Frontend
    needs: files-changed
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: './.tool-versions'
      - name: Frontend | Lint
        run: npm install && npm run test:lint
        working-directory: ./frontend

  unit:
    if: needs.files-changed.outputs.frontend == 'true'
    name: Unit - Frontend
    needs: files-changed
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: './.tool-versions'
      - name: Frontend | Unit
        run: npm install && npm run test:unit
        working-directory: ./frontend
