name: presenter

on: push

jobs:
  files-changed:
    name: Detect File Changes - presenter/
    runs-on: ubuntu-latest
    outputs:
      presenter: ${{ steps.filter.outputs.presenter }}
    steps:
      - uses: actions/checkout@6d193bf28034eafb982f37bd894289fe649468fc # v4.1.7
      - uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36 # v3.0.2
        id: filter
        with:
          filters: |
            presenter:
              - '.github/workflows/**/*'
              - 'presenter/**/*'

  build:
    if: needs.files-changed.outputs.presenter == 'true'
    name: Build - Presenter
    needs: files-changed
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@6d193bf28034eafb982f37bd894289fe649468fc # v4.1.7
      - uses: actions/setup-node@97ca147735c170fb35096b39ef17a0fc5d9270ac # v4.0.3
        with:
          node-version-file: './.tool-versions'
      - name: Presenter | Build
        run: npm install && npm run build
        working-directory: ./presenter

  storybook:
    if: needs.files-changed.outputs.presenter == 'true'
    name: Build Storybook - Presenter
    needs: files-changed
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@6d193bf28034eafb982f37bd894289fe649468fc # v4.1.7
      - uses: actions/setup-node@97ca147735c170fb35096b39ef17a0fc5d9270ac # v4.0.3
        with:
          node-version-file: './.tool-versions'
      - name: Presenter | Build Storybook
        run: npm install && npm run storybook:build
        working-directory: ./presenter

  lint:
    if: needs.files-changed.outputs.presenter == 'true'
    name: Lint - Presenter
    needs: files-changed
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@6d193bf28034eafb982f37bd894289fe649468fc # v4.1.7
      - uses: actions/setup-node@97ca147735c170fb35096b39ef17a0fc5d9270ac # v4.0.3
        with:
          node-version-file: './.tool-versions'
      - name: Presenter | Lint
        run: npm install && npm run test:lint
        working-directory: ./presenter

  unit:
    if: needs.files-changed.outputs.presenter == 'true'
    name: Unit - Presenter
    needs: files-changed
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@6d193bf28034eafb982f37bd894289fe649468fc # v4.1.7
      - uses: actions/setup-node@97ca147735c170fb35096b39ef17a0fc5d9270ac # v4.0.3
        with:
          node-version-file: './.tool-versions'
      - name: Presenter | Unit
        run: npm install && npm run test:unit
        working-directory: ./presenter
