name: "presenter:deploy:chromatic"
on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    name: Chromatic - Presenter
    runs-on: ubuntu-latest
    env:
      CHROMATIC_PROJECT_TOKEN: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
      WORKING_DIRECTORY: ./presenter
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Presenter | Build
        run: npm install && npm run chromatic -- --exit-zero-on-changes
        working-directory: ${{env.WORKING_DIRECTORY}}