name: "dreammall:test:code with defined tests & linters"

on: [push,pull_request_target]

jobs:
  files-changed:
    name: Detect File Changes
    runs-on: ubuntu-latest
    outputs:
      markdown: ${{ steps.filter.outputs.markdown }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3.0.2
        id: filter
        with:
          filters: |
            markdown:
              - '/**/*.md'

  test:
    if: needs.files-changed.outputs.markdown == 'true'
    name: Test - Code
    needs: files-changed
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: './.tool-versions'
      - name: Code | Test
        run: npm install && npm test
