name: "dreammall:test:code with defined tests & linters"

on: [push,pull_request_target]

jobs:
  files-changed:
    name: Detect File Changes
    runs-on: ubuntu-latest
    outputs:
      docs: ${{ steps.filter.outputs.docs }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3.0.2
        id: filter
        with:
          filters: |
            docs:
              - '.github/workflows/**/*'
              - '**/*.md'
              - '.vuepress/*'
              - 'package.json'

  test:
    if: needs.files-changed.outputs.docs == 'true'
    name: Root - Test
    needs: files-changed
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Test | Root
        run: npm install && npm test

  docs:
    if: needs.files-changed.outputs.docs == 'true'
    name: Build Docs - Root
    needs: files-changed
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Root | Build Docs
        run: npm install && npm run docs:build
